### PR TITLE
Accessibility branch

### PR DESCRIPTION
**Pull request by Wils-FOURR-speed**
This branch of the portfolio had to deal with changing the title of the page and implementing good alt text for all the image tags in case the users can't see image itself.

Below is the report:

- Page titles - Changed title 
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#LL8C21-L8C21

- image text alternatives
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L47-L51
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L55
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L177
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L180
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L195
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L204 
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L215
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L229
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L266-L268
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L273-L277
  https://github.com/Wils-FOURR-speed/My-portfolio/blob/Accessibility_branch/index.html#L284-L288

- Text headings - No issues found

- Color contrast  - No issues found

- Resize - No issues found
- Interaction - No issues found
- Moving content - No issues found
- Multimedia - No issues found
- Basic structure of page -  No issues found

### CODE REVIEW

**Review by Ibizugbe — COMMENTED** [review]
Hi @Wils-FOURR-speed  @hetrox8 👋👋👋, 

INVALID


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

This is a pair programming activity and the work and submission mode states that only one repository is submitted on behalf of the group😉. If you have made the necessary changes requested by the previous reviewers, kindly submit the same repository you submitted ealier on👍.
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Wils-FOURR-speed** [comment]
Ohh okay. Thanks for the explanation. I thought both repositories had to be
reviewed.

**Comment by hetrox8** [comment]
i dont get it . you just gave me a review

**Comment by Ibizugbe** [comment]
@hetrox8 , Yeahh true.. I have you a review, hence that same PR should be submitted for a Re-review for the sake of consistency.👍

**Pull request merged**
